#!/bin/sh
#

if [ "$1" == "start"  ]; then

if [ -f "/secondboot" ]; then
	echo "Second boot... ";
	rm /secondboot
	/usr/sbin/mkfs.ext2 /dev/mmcblk0p3
	mkdir /rpicopter
	echo "/dev/mmcblk0p3       /rpicopter              ext2	async,rw,noauto         0      0" >> /etc/fstab
	echo "Second boot done!";
	sync;sync;/sbin/reboot;
fi

if [ -f "/firstboot" ]; then
	echo "First boot... ";
	rm /firstboot
	(echo n;echo p;echo 3;echo ;echo ;echo w;) | /sbin/fdisk /dev/mmcblk0
	touch /secondboot
	echo "First boot done!";
	sync;sync;/sbin/reboot;
fi


fi

exit 0
